const languageToFlag = {
    ar: 'ae',
    bn: 'bd',
    ca: 'es',
    cs: 'cz',
    da: 'dk',
    de: 'de',
    el: 'gr',
    en: 'us',
    es: 'es',
    et: 'ee',
    fa: 'ir',
    fi: 'fi',
    fr: 'fr',
    gu: 'in',
    he: 'il',
    hi: 'in',
    hr: 'hr',
    hu: 'hu',
    id: 'id',
    it: 'it',
    ja: 'jp',
    kn: 'in',
    ko: 'kr',
    lt: 'lt',
    lv: 'lv',
    ml: 'in',
    mr: 'in',
    ms: 'my',
    mt: 'mt',
    nl: 'nl',
    no: 'no',
    pl: 'pl',
    pt: 'pt',
    ro: 'ro',
    ru: 'ru',
    sk: 'sk',
    sl: 'sl',
    sr: 'rs',
    sv: 'se',
    sw: 'tz',
    ta: 'in',
    te: 'in',
    th: 'th',
    tr: 'tr',
    uk: 'ua',
    vi: 'vn',
    zh: 'cn',
    zu: 'za',
    
};

export function getFlagCode(language) {
    return languageToFlag[language] || language;
}